android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8

GROUP=dev.caferati
POM_ARTIFACT_ID=awesome-button-compose
VERSION_NAME=1.1.0

POM_NAME=Awesome Button Compose
POM_DESCRIPTION=Android Jetpack Compose implementation of the Awesome Button component family.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/rcaferati/kotlin-awesome-button

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/mit
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/rcaferati/kotlin-awesome-button
POM_SCM_CONNECTION=scm:git:https://github.com/rcaferati/kotlin-awesome-button.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/rcaferati/kotlin-awesome-button.git

POM_DEVELOPER_ID=rcaferati
POM_DEVELOPER_NAME=Rafael Caferati
POM_DEVELOPER_URL=https://github.com/rcaferati
